# Kurtosis network configuration for contributoor beacon node integration testing
# This configuration creates a minimal testnet with one instance of each major beacon client
participants:
  # Teku beacon node
  - el_type: geth
    cl_type: teku
    cl_image: ethpandaops/teku:master
    count: 1

  # Prysm beacon node
  - el_type: geth
    cl_type: prysm
    cl_image: ethpandaops/prysm-beacon-chain:develop
    count: 1

  # Lighthouse beacon node
  - el_type: geth
    cl_type: lighthouse
    cl_image: ethpandaops/lighthouse:unstable
    count: 1

  # Nimbus beacon node
  - el_type: geth
    cl_type: nimbus
    cl_image: ethpandaops/nimbus-eth2:multiarch-v25.11.1
    count: 1

  # Lodestar beacon node
  - el_type: geth
    cl_type: lodestar
    cl_image: ethpandaops/lodestar:unstable
    count: 1

  # Grandine beacon node
  - el_type: geth
    cl_type: grandine
    cl_image: ethpandaops/grandine:develop
    count: 1

additional_services: []

